// TODO: Voir pour transformer chaque filtre en object qui contiendrai {type: string, active: bool, order: number},
//  voir egalement si on a reelement besoin de ce fichier apres la connection au XMS
export const filterItemType = {
  doors: {
    type: 'button',
    variant: 'vertical',
    label: {
      en: 'Doors',
      fr: 'Portes',
    },
    order: null,
    active: true,
  },
  driveTrainId: {
    type: 'button',
    variant: 'horizontal',
    label: {
      en: 'Drivetrain',
      fr: 'Transmission',
    },
    order: 1,
    active: false,
  },
  // engineDescriptionsId: '',
  // engineId: '',
  // frameCategoryId: '',
  frameStyleId: {
    type: 'button',
    variant: 'horizontal',
    label: {
      en: 'Bodystyles',
      fr: 'Carrosseries',
    },
    order: 2,
    active: false,
  },
  fuelId: {
    type: 'button',
    variant: 'horizontal',
    label: {
      en: 'Energy',
      fr: 'Carburant',
    },
    order: 3,
    active: false,
  },
  // inventoryId: '',
  // makeId: 'button',
  // modelId: 'button',
  passengers: {
    type: 'button',
    variant: 'vertical',
    label: {
      en: 'Passengers',
      fr: 'Passagers',
    },
    order: null,
    active: true,
  },
  // primaryOrganizationUnitId: '',
  transmissionId: {
    type: 'button',
    variant: 'vertical',
    label: {
      en: 'Transmission',
      fr: 'Traction',
    },
    order: 4,
    active: true,
  },
  // trimId: '',
  // vehicleCategoryId: '',
  year: {
    type: 'dropdown',
    variant: 'doubleInput',
    label: {
      en: 'Year',
      fr: 'Année',
    },
    title: {
      en: 'Select Year',
      fr: 'Selectionner votre année',
    },
    placeholder: '',
    filterMinSlug: 'minYear',
    filterMaxSlug: 'maxYear',
    formatNumberType: '',
    step: 1,
    order: 6,
    active: true,
  },
  exteriorColorId: {
    type: 'color',
    variant: '',
    label: {
      en: 'Exterior Colors',
      fr: 'Couleurs extérieures',
    },
    order: 5,
    active: true,
  },
  interiorColorId: {
    type: 'color',
    variant: '',
    label: {
      en: 'Interior Colors',
      fr: 'Couleurs intérieures',
    },
    order: 6,
    active: true,
  },
  // odometerRange: '',
  odometerRangeAll: {
    type: 'range',
    variant: 'doubleRange',
    label: {
      en: 'Odometer',
      fr: 'Odomètre',
    },
    title: {
      en: 'Set Your Mileage',
      fr: 'Configurer votre odomètre',
    },
    placeholder: 'km',
    filterMinSlug: 'minOdometer',
    filterMaxSlug: 'maxOdometer',
    formatNumberType: 'number',
    step: 1,
    order: 6,
    active: true,
  },
  // priceRange: '',
  priceRangeAll: {
    type: 'input',
    variant: 'doubleInput',
    label: {
      en: 'Price',
      fr: 'Prix',
    },
    title: {
      en: 'Set Your Price',
      fr: 'Configurer votre prix',
    },
    placeholder: '$',
    filterMinSlug: 'minPrice',
    filterMaxSlug: 'maxPrice',
    formatNumberType: 'number',
    step: 1000,
    order: 6,
    active: true,
  },
  // yearRange: '',
  yearRangeAll: {
    type: 'range',
    variant: 'doubleRange',
    label: {
      en: 'Year',
      fr: 'Année',
    },
    title: {
      en: 'Set Your Year',
      fr: 'Configurer votre année',
    },
    hasSpecificValue: true,
    placeholder: '',
    filterMinSlug: 'minYear',
    filterMaxSlug: 'maxYear',
    formatNumberType: '',
    step: 1,
    order: 6,
    active: false,
  },
  // odometerBuckets: '',
  // priceBuckets: '',
}
